[package]
name = "ncl-loader"
description = "NCL ModLoader trait + Forge / Fabric / NeoForge implementations"
version.workspace = true
edition.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
ncl-core = { workspace = true }
ncl-net = { workspace = true }
ncl-task = { workspace = true }
ncl-vanilla = { workspace = true }
ncl-java = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
reqwest = { workspace = true }
async-trait = { workspace = true }
tracing = { workspace = true }
thiserror = { workspace = true }
zip = { workspace = true }
